//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPages.RunServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ewide.com", ConfigurationName="RunServiceReference.RunServiceSoap")]
    public interface RunServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/UserLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UserLogin(string userData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/UserRegister", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UserRegister(string userData);
        
        // CODEGEN: 消息 UserPlaceOrderRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/UserPlaceOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.UserPlaceOrderResponse UserPlaceOrder(WebPages.RunServiceReference.UserPlaceOrderRequest request);
        
        // CODEGEN: 消息 SearchUnCompleteOrderRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/SearchUnCompleteOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.SearchUnCompleteOrderResponse SearchUnCompleteOrder(WebPages.RunServiceReference.SearchUnCompleteOrderRequest request);
        
        // CODEGEN: 消息 SearchUnCompleteOrder2Request 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/SearchUnCompleteOrder2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.SearchUnCompleteOrder2Response SearchUnCompleteOrder2(WebPages.RunServiceReference.SearchUnCompleteOrder2Request request);
        
        // CODEGEN: 消息 SearchCompleteOrderRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/SearchCompleteOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.SearchCompleteOrderResponse SearchCompleteOrder(WebPages.RunServiceReference.SearchCompleteOrderRequest request);
        
        // CODEGEN: 消息 DeleteUnTakedOrderRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/DeleteUnTakedOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.DeleteUnTakedOrderResponse DeleteUnTakedOrder(WebPages.RunServiceReference.DeleteUnTakedOrderRequest request);
        
        // CODEGEN: 消息 AddCommentRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/AddComment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.AddCommentResponse AddComment(WebPages.RunServiceReference.AddCommentRequest request);
        
        // CODEGEN: 消息 SearchMapPointRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/SearchMapPoint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.SearchMapPointResponse SearchMapPoint(WebPages.RunServiceReference.SearchMapPointRequest request);
        
        // CODEGEN: 消息 UserTakeOrderRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/UserTakeOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.UserTakeOrderResponse UserTakeOrder(WebPages.RunServiceReference.UserTakeOrderRequest request);
        
        // CODEGEN: 消息 SearchUnCompleteTakedOrderRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/SearchUnCompleteTakedOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.SearchUnCompleteTakedOrderResponse SearchUnCompleteTakedOrder(WebPages.RunServiceReference.SearchUnCompleteTakedOrderRequest request);
        
        // CODEGEN: 消息 SearchCompleteTakedOrderRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/SearchCompleteTakedOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.SearchCompleteTakedOrderResponse SearchCompleteTakedOrder(WebPages.RunServiceReference.SearchCompleteTakedOrderRequest request);
        
        // CODEGEN: 消息 BackTakedOrderRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/BackTakedOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.BackTakedOrderResponse BackTakedOrder(WebPages.RunServiceReference.BackTakedOrderRequest request);
        
        // CODEGEN: 消息 completeTakedOrderRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/completeTakedOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.completeTakedOrderResponse completeTakedOrder(WebPages.RunServiceReference.completeTakedOrderRequest request);
        
        // CODEGEN: 消息 GetPointRouteRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/GetPointRoute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.GetPointRouteResponse GetPointRoute(WebPages.RunServiceReference.GetPointRouteRequest request);
        
        // CODEGEN: 消息 SearchCommentRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/SearchComment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.SearchCommentResponse SearchComment(WebPages.RunServiceReference.SearchCommentRequest request);
        
        // CODEGEN: 消息 GetCommentRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/GetComment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.GetCommentResponse GetComment(WebPages.RunServiceReference.GetCommentRequest request);
        
        // CODEGEN: 消息 GetOrderRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/GetOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.GetOrderResponse GetOrder(WebPages.RunServiceReference.GetOrderRequest request);
        
        // CODEGEN: 消息 ModifyUserTypeRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/ModifyUserType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.ModifyUserTypeResponse ModifyUserType(WebPages.RunServiceReference.ModifyUserTypeRequest request);
        
        // CODEGEN: 消息 SearchUserByTypeRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ewide.com/SearchUserByType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebPages.RunServiceReference.SearchUserByTypeResponse SearchUserByType(WebPages.RunServiceReference.SearchUserByTypeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ewide.com")]
    public partial class MySoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserPlaceOrder", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class UserPlaceOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public UserPlaceOrderRequest() {
        }
        
        public UserPlaceOrderRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserPlaceOrderResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class UserPlaceOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string UserPlaceOrderResult;
        
        public UserPlaceOrderResponse() {
        }
        
        public UserPlaceOrderResponse(string UserPlaceOrderResult) {
            this.UserPlaceOrderResult = UserPlaceOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchUnCompleteOrder", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchUnCompleteOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public SearchUnCompleteOrderRequest() {
        }
        
        public SearchUnCompleteOrderRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchUnCompleteOrderResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchUnCompleteOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string SearchUnCompleteOrderResult;
        
        public SearchUnCompleteOrderResponse() {
        }
        
        public SearchUnCompleteOrderResponse(string SearchUnCompleteOrderResult) {
            this.SearchUnCompleteOrderResult = SearchUnCompleteOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchUnCompleteOrder2", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchUnCompleteOrder2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public SearchUnCompleteOrder2Request() {
        }
        
        public SearchUnCompleteOrder2Request(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchUnCompleteOrder2Response", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchUnCompleteOrder2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string SearchUnCompleteOrder2Result;
        
        public SearchUnCompleteOrder2Response() {
        }
        
        public SearchUnCompleteOrder2Response(string SearchUnCompleteOrder2Result) {
            this.SearchUnCompleteOrder2Result = SearchUnCompleteOrder2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchCompleteOrder", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchCompleteOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public SearchCompleteOrderRequest() {
        }
        
        public SearchCompleteOrderRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchCompleteOrderResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchCompleteOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string SearchCompleteOrderResult;
        
        public SearchCompleteOrderResponse() {
        }
        
        public SearchCompleteOrderResponse(string SearchCompleteOrderResult) {
            this.SearchCompleteOrderResult = SearchCompleteOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteUnTakedOrder", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class DeleteUnTakedOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public DeleteUnTakedOrderRequest() {
        }
        
        public DeleteUnTakedOrderRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteUnTakedOrderResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class DeleteUnTakedOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string DeleteUnTakedOrderResult;
        
        public DeleteUnTakedOrderResponse() {
        }
        
        public DeleteUnTakedOrderResponse(string DeleteUnTakedOrderResult) {
            this.DeleteUnTakedOrderResult = DeleteUnTakedOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddComment", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class AddCommentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public AddCommentRequest() {
        }
        
        public AddCommentRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCommentResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class AddCommentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string AddCommentResult;
        
        public AddCommentResponse() {
        }
        
        public AddCommentResponse(string AddCommentResult) {
            this.AddCommentResult = AddCommentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchMapPoint", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchMapPointRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public SearchMapPointRequest() {
        }
        
        public SearchMapPointRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchMapPointResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchMapPointResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string SearchMapPointResult;
        
        public SearchMapPointResponse() {
        }
        
        public SearchMapPointResponse(string SearchMapPointResult) {
            this.SearchMapPointResult = SearchMapPointResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserTakeOrder", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class UserTakeOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public UserTakeOrderRequest() {
        }
        
        public UserTakeOrderRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserTakeOrderResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class UserTakeOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string UserTakeOrderResult;
        
        public UserTakeOrderResponse() {
        }
        
        public UserTakeOrderResponse(string UserTakeOrderResult) {
            this.UserTakeOrderResult = UserTakeOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchUnCompleteTakedOrder", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchUnCompleteTakedOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public SearchUnCompleteTakedOrderRequest() {
        }
        
        public SearchUnCompleteTakedOrderRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchUnCompleteTakedOrderResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchUnCompleteTakedOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string SearchUnCompleteTakedOrderResult;
        
        public SearchUnCompleteTakedOrderResponse() {
        }
        
        public SearchUnCompleteTakedOrderResponse(string SearchUnCompleteTakedOrderResult) {
            this.SearchUnCompleteTakedOrderResult = SearchUnCompleteTakedOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchCompleteTakedOrder", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchCompleteTakedOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public SearchCompleteTakedOrderRequest() {
        }
        
        public SearchCompleteTakedOrderRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchCompleteTakedOrderResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchCompleteTakedOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string SearchCompleteTakedOrderResult;
        
        public SearchCompleteTakedOrderResponse() {
        }
        
        public SearchCompleteTakedOrderResponse(string SearchCompleteTakedOrderResult) {
            this.SearchCompleteTakedOrderResult = SearchCompleteTakedOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BackTakedOrder", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class BackTakedOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public BackTakedOrderRequest() {
        }
        
        public BackTakedOrderRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BackTakedOrderResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class BackTakedOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string BackTakedOrderResult;
        
        public BackTakedOrderResponse() {
        }
        
        public BackTakedOrderResponse(string BackTakedOrderResult) {
            this.BackTakedOrderResult = BackTakedOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="completeTakedOrder", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class completeTakedOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public completeTakedOrderRequest() {
        }
        
        public completeTakedOrderRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="completeTakedOrderResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class completeTakedOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string completeTakedOrderResult;
        
        public completeTakedOrderResponse() {
        }
        
        public completeTakedOrderResponse(string completeTakedOrderResult) {
            this.completeTakedOrderResult = completeTakedOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPointRoute", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class GetPointRouteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public GetPointRouteRequest() {
        }
        
        public GetPointRouteRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPointRouteResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class GetPointRouteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string GetPointRouteResult;
        
        public GetPointRouteResponse() {
        }
        
        public GetPointRouteResponse(string GetPointRouteResult) {
            this.GetPointRouteResult = GetPointRouteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchComment", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchCommentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        public SearchCommentRequest() {
        }
        
        public SearchCommentRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader) {
            this.MySoapHeader = MySoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchCommentResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchCommentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string SearchCommentResult;
        
        public SearchCommentResponse() {
        }
        
        public SearchCommentResponse(string SearchCommentResult) {
            this.SearchCommentResult = SearchCommentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetComment", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class GetCommentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public GetCommentRequest() {
        }
        
        public GetCommentRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCommentResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class GetCommentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string GetCommentResult;
        
        public GetCommentResponse() {
        }
        
        public GetCommentResponse(string GetCommentResult) {
            this.GetCommentResult = GetCommentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrder", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class GetOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public GetOrderRequest() {
        }
        
        public GetOrderRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOrderResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class GetOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string GetOrderResult;
        
        public GetOrderResponse() {
        }
        
        public GetOrderResponse(string GetOrderResult) {
            this.GetOrderResult = GetOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyUserType", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class ModifyUserTypeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public ModifyUserTypeRequest() {
        }
        
        public ModifyUserTypeRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyUserTypeResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class ModifyUserTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string ModifyUserTypeResult;
        
        public ModifyUserTypeResponse() {
        }
        
        public ModifyUserTypeResponse(string ModifyUserTypeResult) {
            this.ModifyUserTypeResult = ModifyUserTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchUserByType", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchUserByTypeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ewide.com")]
        public WebPages.RunServiceReference.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string userData;
        
        public SearchUserByTypeRequest() {
        }
        
        public SearchUserByTypeRequest(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            this.MySoapHeader = MySoapHeader;
            this.userData = userData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchUserByTypeResponse", WrapperNamespace="http://www.ewide.com", IsWrapped=true)]
    public partial class SearchUserByTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewide.com", Order=0)]
        public string SearchUserByTypeResult;
        
        public SearchUserByTypeResponse() {
        }
        
        public SearchUserByTypeResponse(string SearchUserByTypeResult) {
            this.SearchUserByTypeResult = SearchUserByTypeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RunServiceSoapChannel : WebPages.RunServiceReference.RunServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RunServiceSoapClient : System.ServiceModel.ClientBase<WebPages.RunServiceReference.RunServiceSoap>, WebPages.RunServiceReference.RunServiceSoap {
        
        public RunServiceSoapClient() {
        }
        
        public RunServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RunServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RunServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RunServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UserLogin(string userData) {
            return base.Channel.UserLogin(userData);
        }
        
        public string UserRegister(string userData) {
            return base.Channel.UserRegister(userData);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.UserPlaceOrderResponse WebPages.RunServiceReference.RunServiceSoap.UserPlaceOrder(WebPages.RunServiceReference.UserPlaceOrderRequest request) {
            return base.Channel.UserPlaceOrder(request);
        }
        
        public string UserPlaceOrder(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.UserPlaceOrderRequest inValue = new WebPages.RunServiceReference.UserPlaceOrderRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.UserPlaceOrderResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).UserPlaceOrder(inValue);
            return retVal.UserPlaceOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.SearchUnCompleteOrderResponse WebPages.RunServiceReference.RunServiceSoap.SearchUnCompleteOrder(WebPages.RunServiceReference.SearchUnCompleteOrderRequest request) {
            return base.Channel.SearchUnCompleteOrder(request);
        }
        
        public string SearchUnCompleteOrder(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.SearchUnCompleteOrderRequest inValue = new WebPages.RunServiceReference.SearchUnCompleteOrderRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.SearchUnCompleteOrderResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).SearchUnCompleteOrder(inValue);
            return retVal.SearchUnCompleteOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.SearchUnCompleteOrder2Response WebPages.RunServiceReference.RunServiceSoap.SearchUnCompleteOrder2(WebPages.RunServiceReference.SearchUnCompleteOrder2Request request) {
            return base.Channel.SearchUnCompleteOrder2(request);
        }
        
        public string SearchUnCompleteOrder2(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.SearchUnCompleteOrder2Request inValue = new WebPages.RunServiceReference.SearchUnCompleteOrder2Request();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.SearchUnCompleteOrder2Response retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).SearchUnCompleteOrder2(inValue);
            return retVal.SearchUnCompleteOrder2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.SearchCompleteOrderResponse WebPages.RunServiceReference.RunServiceSoap.SearchCompleteOrder(WebPages.RunServiceReference.SearchCompleteOrderRequest request) {
            return base.Channel.SearchCompleteOrder(request);
        }
        
        public string SearchCompleteOrder(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.SearchCompleteOrderRequest inValue = new WebPages.RunServiceReference.SearchCompleteOrderRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.SearchCompleteOrderResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).SearchCompleteOrder(inValue);
            return retVal.SearchCompleteOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.DeleteUnTakedOrderResponse WebPages.RunServiceReference.RunServiceSoap.DeleteUnTakedOrder(WebPages.RunServiceReference.DeleteUnTakedOrderRequest request) {
            return base.Channel.DeleteUnTakedOrder(request);
        }
        
        public string DeleteUnTakedOrder(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.DeleteUnTakedOrderRequest inValue = new WebPages.RunServiceReference.DeleteUnTakedOrderRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.DeleteUnTakedOrderResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).DeleteUnTakedOrder(inValue);
            return retVal.DeleteUnTakedOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.AddCommentResponse WebPages.RunServiceReference.RunServiceSoap.AddComment(WebPages.RunServiceReference.AddCommentRequest request) {
            return base.Channel.AddComment(request);
        }
        
        public string AddComment(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.AddCommentRequest inValue = new WebPages.RunServiceReference.AddCommentRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.AddCommentResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).AddComment(inValue);
            return retVal.AddCommentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.SearchMapPointResponse WebPages.RunServiceReference.RunServiceSoap.SearchMapPoint(WebPages.RunServiceReference.SearchMapPointRequest request) {
            return base.Channel.SearchMapPoint(request);
        }
        
        public string SearchMapPoint(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.SearchMapPointRequest inValue = new WebPages.RunServiceReference.SearchMapPointRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.SearchMapPointResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).SearchMapPoint(inValue);
            return retVal.SearchMapPointResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.UserTakeOrderResponse WebPages.RunServiceReference.RunServiceSoap.UserTakeOrder(WebPages.RunServiceReference.UserTakeOrderRequest request) {
            return base.Channel.UserTakeOrder(request);
        }
        
        public string UserTakeOrder(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.UserTakeOrderRequest inValue = new WebPages.RunServiceReference.UserTakeOrderRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.UserTakeOrderResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).UserTakeOrder(inValue);
            return retVal.UserTakeOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.SearchUnCompleteTakedOrderResponse WebPages.RunServiceReference.RunServiceSoap.SearchUnCompleteTakedOrder(WebPages.RunServiceReference.SearchUnCompleteTakedOrderRequest request) {
            return base.Channel.SearchUnCompleteTakedOrder(request);
        }
        
        public string SearchUnCompleteTakedOrder(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.SearchUnCompleteTakedOrderRequest inValue = new WebPages.RunServiceReference.SearchUnCompleteTakedOrderRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.SearchUnCompleteTakedOrderResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).SearchUnCompleteTakedOrder(inValue);
            return retVal.SearchUnCompleteTakedOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.SearchCompleteTakedOrderResponse WebPages.RunServiceReference.RunServiceSoap.SearchCompleteTakedOrder(WebPages.RunServiceReference.SearchCompleteTakedOrderRequest request) {
            return base.Channel.SearchCompleteTakedOrder(request);
        }
        
        public string SearchCompleteTakedOrder(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.SearchCompleteTakedOrderRequest inValue = new WebPages.RunServiceReference.SearchCompleteTakedOrderRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.SearchCompleteTakedOrderResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).SearchCompleteTakedOrder(inValue);
            return retVal.SearchCompleteTakedOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.BackTakedOrderResponse WebPages.RunServiceReference.RunServiceSoap.BackTakedOrder(WebPages.RunServiceReference.BackTakedOrderRequest request) {
            return base.Channel.BackTakedOrder(request);
        }
        
        public string BackTakedOrder(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.BackTakedOrderRequest inValue = new WebPages.RunServiceReference.BackTakedOrderRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.BackTakedOrderResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).BackTakedOrder(inValue);
            return retVal.BackTakedOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.completeTakedOrderResponse WebPages.RunServiceReference.RunServiceSoap.completeTakedOrder(WebPages.RunServiceReference.completeTakedOrderRequest request) {
            return base.Channel.completeTakedOrder(request);
        }
        
        public string completeTakedOrder(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.completeTakedOrderRequest inValue = new WebPages.RunServiceReference.completeTakedOrderRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.completeTakedOrderResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).completeTakedOrder(inValue);
            return retVal.completeTakedOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.GetPointRouteResponse WebPages.RunServiceReference.RunServiceSoap.GetPointRoute(WebPages.RunServiceReference.GetPointRouteRequest request) {
            return base.Channel.GetPointRoute(request);
        }
        
        public string GetPointRoute(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.GetPointRouteRequest inValue = new WebPages.RunServiceReference.GetPointRouteRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.GetPointRouteResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).GetPointRoute(inValue);
            return retVal.GetPointRouteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.SearchCommentResponse WebPages.RunServiceReference.RunServiceSoap.SearchComment(WebPages.RunServiceReference.SearchCommentRequest request) {
            return base.Channel.SearchComment(request);
        }
        
        public string SearchComment(WebPages.RunServiceReference.MySoapHeader MySoapHeader) {
            WebPages.RunServiceReference.SearchCommentRequest inValue = new WebPages.RunServiceReference.SearchCommentRequest();
            inValue.MySoapHeader = MySoapHeader;
            WebPages.RunServiceReference.SearchCommentResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).SearchComment(inValue);
            return retVal.SearchCommentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.GetCommentResponse WebPages.RunServiceReference.RunServiceSoap.GetComment(WebPages.RunServiceReference.GetCommentRequest request) {
            return base.Channel.GetComment(request);
        }
        
        public string GetComment(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.GetCommentRequest inValue = new WebPages.RunServiceReference.GetCommentRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.GetCommentResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).GetComment(inValue);
            return retVal.GetCommentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.GetOrderResponse WebPages.RunServiceReference.RunServiceSoap.GetOrder(WebPages.RunServiceReference.GetOrderRequest request) {
            return base.Channel.GetOrder(request);
        }
        
        public string GetOrder(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.GetOrderRequest inValue = new WebPages.RunServiceReference.GetOrderRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.GetOrderResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).GetOrder(inValue);
            return retVal.GetOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.ModifyUserTypeResponse WebPages.RunServiceReference.RunServiceSoap.ModifyUserType(WebPages.RunServiceReference.ModifyUserTypeRequest request) {
            return base.Channel.ModifyUserType(request);
        }
        
        public string ModifyUserType(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.ModifyUserTypeRequest inValue = new WebPages.RunServiceReference.ModifyUserTypeRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.ModifyUserTypeResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).ModifyUserType(inValue);
            return retVal.ModifyUserTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPages.RunServiceReference.SearchUserByTypeResponse WebPages.RunServiceReference.RunServiceSoap.SearchUserByType(WebPages.RunServiceReference.SearchUserByTypeRequest request) {
            return base.Channel.SearchUserByType(request);
        }
        
        public string SearchUserByType(WebPages.RunServiceReference.MySoapHeader MySoapHeader, string userData) {
            WebPages.RunServiceReference.SearchUserByTypeRequest inValue = new WebPages.RunServiceReference.SearchUserByTypeRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.userData = userData;
            WebPages.RunServiceReference.SearchUserByTypeResponse retVal = ((WebPages.RunServiceReference.RunServiceSoap)(this)).SearchUserByType(inValue);
            return retVal.SearchUserByTypeResult;
        }
    }
}
