//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> CreaterID { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string ProductName { get; set; }
        public string ProductWeight { get; set; }
        public string SenderName { get; set; }
        public string SenderPhone { get; set; }
        public string SenderAddress { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverPhone { get; set; }
        public string ReceiverAddress { get; set; }
        public Nullable<int> TakerID { get; set; }
        public Nullable<System.DateTime> TakeStartDateTime { get; set; }
        public Nullable<System.DateTime> TakeEndDateTime { get; set; }
        public Nullable<int> State { get; set; }
        public string Remarks { get; set; }
        public string PointX { get; set; }
        public string PointY { get; set; }
        public string PointX2 { get; set; }
        public string PointY2 { get; set; }
        public string Street { get; set; }
    }
}
